# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/asecurityteam/runhttp"
  branch = "master"

[[constraint]]
  name = "github.com/asecurityteam/settings"
  branch = "master"

[[constraint]]
  name = "github.com/getkin/kin-openapi"
  version = "0.1.0"

[[constraint]]
  name = "github.com/asecurityteam/transport"
  version = "1.1.2"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.2.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "2.0.1"

[[constraint]]
  name = "github.com/SermoDigital/jose"
  version = "1.1.0"

[[constraint]]
  name = "bitbucket.org/atlassian/go-asap"
  version = "2.2.0"
  source = "https://bitbucket.org/atlassian/go-asap.git"

[[constraint]]
  name = "github.com/asecurityteam/httpstats"
  version = "2.1.1"
