on: [push, pull_request]
name: Build and Test
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up GO
        uses: actions/setup-go@v2
        with:
          go-version: 1.13

      - name: Setup directory permissions
        run: chmod 777 -R "$(pwd)"

      - name: Install Dependencies
        run: make dep

      - name: Lint
        run: make test

      - name: Integration
        run: make integration

      - name: Coverage
        run: make coverage

      - name: Upload Coverage Results
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash) -f .coverage/combined.cover.out
