on: [push, pull_reuqest]
name: Build and Test
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: action/checkout@v2

      - name: Set up GO
        uses: actions/setup-go@v2
        with:
          go-version: 1.13